controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    wam_model_controller:
      type: wam_model_controller/WamModelController

arm_controller:
  ros__parameters:
    joints:
      - wam/base_yaw_joint
      - wam/shoulder_pitch_joint
      - wam/shoulder_yaw_joint
      - wam/elbow_pitch_joint
      - wam/wrist_yaw_joint
      - wam/wrist_pitch_joint
      - wam/palm_yaw_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

wam_model_controller:
  ros__parameters:
    hold_current_position: true

    q_des:
      - 0.0
      - 0.0
      - 0.0
      - 1.5
      - 0.0
      - 0.0
      - 0.0

    kp:
      - 50.0
      - 80.0
      - 50.0
      - 40.0
      - 10.0
      - 10.0
      - 5.0

    kd:
      - 5.0
      - 8.0
      - 5.0
      - 4.0
      - 1.0
      - 1.0
      - 0.5

    torque_limits:
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 10.0
      - 10.0
      - 5.0