controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


arm_controller:
  ros__parameters:
    joints:
      - wam/base_yaw_joint
      - wam/shoulder_pitch_joint
      - wam/shoulder_yaw_joint
      - wam/elbow_pitch_joint
      - wam/wrist_yaw_joint
      - wam/wrist_pitch_joint
      - wam/palm_yaw_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
